export const queryKeys = {
  websiteProjects: ["website-projects"] as const,
  dashboard: (projectId: string | null) => ["dashboard", projectId] as const,
  settings: ["settings"] as const,
  studio: (projectId: string | null) => ["studio", projectId] as const,
  contentPieces: (projectId: string | null) => ["content-pieces", projectId] as const,
  aiProviderStatus: ["ai-provider-status"] as const,
  brandProfile: (projectId: string | null) => ["brand-profile", projectId] as const,
  stockCredentials: ["stock-credentials"] as const,
  integrations: (projectId: string | null) => ["integrations", projectId] as const,
  projectsEnriched: ["projects-enriched"] as const,
  projectDetail: (projectId: string | undefined) => ["project-detail", projectId] as const,
  contentPiece: (pieceId: string | undefined) => ["content-piece", pieceId] as const,
  projectBrandProfile: (projectId: string | null) => ["project-brand-profile", projectId] as const,
  keywordAlerts: (projectId: string | null) => ["keyword-alerts", projectId] as const,
  keywordSnapshots: (trackedId: number | null) => ["keyword-snapshots", trackedId] as const,
  articleIdeas: (projectId: string | null) => ["article-ideas", projectId] as const,
  articleIdeaSources: (projectId: string | null) => ["article-idea-sources", projectId] as const,
  gscQueries: (projectId: string | null) => ["gsc-queries", projectId] as const,
  semrushStatus: (projectId: string | null) => ["semrush-status", projectId] as const,
  autopilot: (projectId: string | null) => ["autopilot", projectId] as const,
  auditList: (projectId?: string | null) => ["audit-list", projectId ?? "all"] as const,
  auditDetail: (auditId: string) => ["audit-detail", auditId] as const,
  social: (projectId: string | null, platformFilter: string) =>
    ["social", projectId, platformFilter] as const,
  team: ["team"] as const,
  goals: (projectId: string | null) => ["goals", projectId] as const,
  roadmaps: (limit: number) => ["roadmaps", limit] as const,
  growthRoadmap: (slug: string) => ["growth-roadmap", slug] as const,
  brandKeywords: (projectId: string | null) => ["brand-keywords", projectId] as const,
  trackedKeywords: (projectId: string | null) => ["tracked-keywords", projectId] as const,
  visibilitySettings: (projectId: string | null) => ["visibility-settings", projectId] as const,
  visibilitySummary: (projectId: string | null) => ["visibility-summary", projectId] as const,
  articlePerformance: (projectId: string | null, startDate: string, endDate: string) =>
    ["article-performance", projectId, startDate, endDate] as const,
  briefs: (projectId: string | null) => ["briefs", projectId] as const,
  gscSyncStatus: (projectId: string | null) => ["gsc-sync-status", projectId] as const,
  partnerProjects: ["partner-projects"] as const,
  keywordOpportunities: (projectId: string | null) => ["keyword-opportunities", projectId] as const,
  competitorAnalyses: (projectId: string | null) => ["competitor-analyses", projectId] as const,
  adminOverview: ["admin-overview"] as const,
  adminUsers: (search: string, orgId?: string, role?: string) =>
    ["admin-users", search, orgId ?? "", role ?? ""] as const,
  adminOrganizations: ["admin-organizations"] as const,
  adminOrganization: (id: number) => ["admin-organization", id] as const,
  adminInvites: ["admin-invites"] as const,
  adminPlanQuotas: ["admin-plan-quotas"] as const,
  adminPlatformSettings: ["admin-platform-settings"] as const,
  adminIntegrations: ["admin-integrations"] as const,
  adminContentStrategies: (search: string, orgId: string, unlinked: boolean) =>
    ["admin-content-strategies", search, orgId, unlinked] as const,
  adminContentStrategy: (id: number) => ["admin-content-strategy", id] as const,
};
