import type { ContentFormatType } from "./content-studio-format-data";
import type { LinkedInArchetypeId, LinkedInHookId } from "@workspace/app-shell/studio";
import type { CmsConnectionSnapshot, PublishDestinationId } from "@/lib/projects/publishing-destinations";
import type { ContentPieceRow } from "./content-studio-utils";
import type { BriefContentDraft } from "./use-create-content-modal";

export type CreateContentWizardProps = {
  selectPath: (flow: "create" | "repurpose") => void;
  selectFormat: (type: ContentFormatType) => void;
  loadingCompetitors: boolean;
  competitorUrls: string[];
  competitorAnalyses: Array<{
    competitorUrl: string;
    competitorName: string;
    contentGaps: string[];
    quickWins: string[];
    threatLevel: "low" | "medium" | "high";
  }>;
  addCompetitorUrl: () => void;
  newCompetitorUrl: string;
  setNewCompetitorUrl: (v: string) => void;
  projectId: string;
  projectIndustry: string;
  keyword: string;
  setKeyword: (v: string) => void;
  selectedFormat: ContentFormatType | null;
  intendedDestination: PublishDestinationId | "";
  setIntendedDestination: (v: PublishDestinationId | "") => void;
  cmsConnections: CmsConnectionSnapshot;
  linkedinArchetype: LinkedInArchetypeId | "";
  setLinkedinArchetype: (v: LinkedInArchetypeId | "") => void;
  linkedinHook: LinkedInHookId | "";
  setLinkedinHook: (v: LinkedInHookId | "") => void;
  angleHint: string;
  setAngleHint: (v: string) => void;
  plannedDate: string;
  setPlannedDate: (v: string) => void;
  generating: boolean;
  detectedSections: string[];
  handleContinue: () => void;
  bypassCache: boolean;
  setBypassCache: (v: boolean) => void;
  competitorFocusUrl: string;
  setCompetitorFocusUrl: (v: string) => void;
  initialDraft?: BriefContentDraft | null;
  repurposeFormat: ContentFormatType;
  setRepurposeFormat: (v: ContentFormatType) => void;
  repurposeKeyword: string;
  setRepurposeKeyword: (v: string) => void;
  repurposeContent: string;
  setRepurposeContent: (v: string) => void;
  sourcePieceId: string;
  setSourcePieceId: (v: string) => void;
  loadSourcePiece: (id: string) => void;
  existingPieces: ContentPieceRow[];
  loadingSourcePiece: boolean;
  goNextStable: () => void;
  runGeneration: () => void;
  showBedrockModelPicker: boolean;
  bedrockModel: string;
  setBedrockModel: (v: string) => void;
  saveBedrockModel: boolean;
  setSaveBedrockModel: (v: boolean) => void;
  canManageBedrockModel: boolean;
};
