"use client";

import Link from "next/link";
import { Map, ArrowRight } from "lucide-react";
import { MarketingPageShell } from "@/components/marketing/marketing-page-shell";
import { PageHero } from "@/components/marketing/page-hero";
import { RoadmapGenerator } from "@/components/marketing/roadmap-generator";
import { MarketingSection } from "@/components/marketing/marketing-section";
import { HERO_IMAGES } from "@/lib/marketing/marketing-hero-images";
import { ROADMAPS_PAGE_REFERRER } from "@/lib/projects/roadmap-intent";
import { cardSurfaceClass } from "@/lib/marketing/marketing-surfaces";

const glassCard = cardSurfaceClass("glass");

type RoadmapItem = {
  id: number;
  slug: string;
  industry: string;
  location: string;
  stage: string;
  viewCount: number;
};

type RoadmapsPageClientProps = {
  roadmaps: RoadmapItem[];
};

export function RoadmapsPageClient({ roadmaps }: RoadmapsPageClientProps) {
  return (
    <MarketingPageShell
      hero={
        <PageHero
          badge="Free tool"
          titleLine1="Growth roadmaps"
          titleLine2="for every market"
          description="AI-generated 12-month B2B growth strategies. Free to browse, share, and build on."
          backgroundImage={HERO_IMAGES.roadmaps.hero}
          ctas={[{ label: "Browse roadmaps", href: "#roadmap-generator", variant: "primary" }]}
        />
      }
    >
      <RoadmapGenerator referrer={ROADMAPS_PAGE_REFERRER} />

      <MarketingSection
        bordered
        titleLine1="Browse"
        titleLine2="roadmaps"
        description="Explore strategies generated by other founders and marketers."
        className="py-16"
      >
        {roadmaps.length === 0 ? (
          <div className={`${glassCard} flex flex-col items-center justify-center p-16 text-center`}>
            <Map className="h-10 w-10 text-white/50 mb-3" />
            <p className="font-medium text-white">No roadmaps yet</p>
            <p className="text-sm text-white/65 mt-1">
              Browse the catalog above or sign in to generate a custom roadmap
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {roadmaps.map((r) => (
              <Link key={r.id} href={`/roadmap/${r.slug}`}>
                <div className={`${glassCard} p-5 cursor-pointer`}>
                  <h3 className="font-semibold text-white">{r.industry}</h3>
                  <p className="text-sm text-white/65 mt-0.5">
                    {r.location} · {r.stage} stage
                  </p>
                  <div className="flex items-center justify-between mt-3">
                    <span className="text-xs text-white/50">{r.viewCount} views</span>
                    <span className="text-xs text-primary font-medium flex items-center gap-1">
                      Read <ArrowRight className="h-3 w-3" />
                    </span>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        )}
      </MarketingSection>
    </MarketingPageShell>
  );
}
