"use client";

import Link from "next/link";
import { ArrowRight, TrendingUp } from "lucide-react";
import { MarketingPageShell } from "@/components/marketing/marketing-page-shell";
import { PageHero } from "@/components/marketing/page-hero";
import { MarketingSection } from "@/components/marketing/marketing-section";
import { WaitlistForm } from "@/components/waitlist-form";
import { HERO_IMAGES } from "@/lib/marketing-hero-images";

export type PublicArticleExample = {
  id: number;
  title: string;
  primaryKeyword: string;
  wordCount: number;
};

export type PublicRoadmapExample = {
  slug: string;
  industry: string;
  location: string;
};

const PLACEHOLDER_STORIES = [
  { company: "B2B SaaS startup", metric: "Citation rate", value: "+24%", period: "90 days", industry: "SaaS" },
  { company: "E-commerce brand", metric: "Organic impressions", value: "3.2×", period: "6 months", industry: "E-commerce" },
  { company: "Marketing agency client", metric: "Articles published", value: "48", period: "Q1", industry: "Agency" },
];

type Props = {
  articles: PublicArticleExample[];
  roadmaps: PublicRoadmapExample[];
};

export function SuccessStoriesPageClient({ articles, roadmaps }: Props) {
  return (
    <MarketingPageShell
      hero={
        <PageHero
          badge="Success stories"
          titleLine1="Results teams"
          titleLine2="are building"
          description="Real customer case studies coming soon. Explore public examples and share your results."
          backgroundImage={HERO_IMAGES.roadmaps.hero}
          ctas={[
            { label: "Start free", href: "/signup", variant: "primary" },
            { label: "Browse roadmaps", href: "/roadmaps", variant: "ghost" },
          ]}
        />
      }
    >
      <MarketingSection variant="paper" bordered className="py-16 bg-background" titleLine1="Proof you" titleLine2="can inspect">
        <div className="grid md:grid-cols-2 gap-6 mb-12">
          <div className="paper-card paper-card-hover p-6">
            <h3 className="font-bold text-lg mb-2">Public growth roadmaps</h3>
            <p className="text-sm text-muted-foreground">Browse free 12-month B2B strategies generated by goals.ac.</p>
            {roadmaps.length > 0 && (
              <ul className="mt-3 text-xs text-muted-foreground space-y-1">
                {roadmaps.slice(0, 3).map((r) => (
                  <li key={r.slug}>
                    <Link href={`/roadmap/${r.slug}`} className="text-primary hover:underline">
                      {r.industry} · {r.location}
                    </Link>
                  </li>
                ))}
              </ul>
            )}
            <Link href="/roadmaps" className="inline-flex items-center gap-1 text-xs text-primary mt-4">
              Browse all →
            </Link>
          </div>
          <div className="paper-card p-6">
            <h3 className="font-bold text-lg mb-2">Article quality demo</h3>
            <p className="text-sm text-muted-foreground mb-3">Every draft gets a /100 quality score — structure, citations, schema, and more.</p>
            <div className="flex items-center gap-2 text-emerald-600 font-bold text-2xl">
              <TrendingUp className="h-5 w-5" /> 92/100
            </div>
            {articles.length > 0 && (
              <ul className="mt-4 space-y-2">
                {articles.slice(0, 3).map((a) => (
                  <li key={a.id}>
                    <Link href={`/seo-article/${a.id}`} className="text-sm text-primary hover:underline line-clamp-1">
                      {a.title}
                    </Link>
                    <span className="text-xs text-muted-foreground ml-1">· {a.wordCount} words</span>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>

        <div className="grid md:grid-cols-3 gap-6">
          {PLACEHOLDER_STORIES.map((story) => (
            <div key={story.company} className="paper-card p-6">
              <p className="text-xs text-muted-foreground uppercase tracking-wide mb-2">{story.industry}</p>
              <h3 className="font-bold mb-4">{story.company}</h3>
              <p className="text-3xl font-bold text-primary">{story.value}</p>
              <p className="text-sm text-muted-foreground">{story.metric} · {story.period}</p>
              <p className="text-xs text-muted-foreground mt-4 italic">Full case study coming soon</p>
            </div>
          ))}
        </div>
      </MarketingSection>

      <MarketingSection variant="paper" className="py-16 bg-secondary/20" titleLine1="Share your" titleLine2="results">
        <p className="text-muted-foreground mb-6 max-w-xl">Using goals.ac? Join the waitlist to be featured in our next success story.</p>
        <WaitlistForm featureKey="success-story" buttonLabel="Share my results" />
        <Link href="/signup" className="inline-flex items-center gap-1 text-sm text-primary mt-8 hover:underline">
          Or start free today <ArrowRight className="h-4 w-4" />
        </Link>
      </MarketingSection>
    </MarketingPageShell>
  );
}
