"use client";

import Link from "next/link";
import { ArrowRight, TrendingUp } from "lucide-react";
import { MarketingPageShell } from "@/components/marketing/marketing-page-shell";
import { PageHero } from "@/components/marketing/page-hero";
import { MarketingSection } from "@/components/marketing/marketing-section";
import { WaitlistForm } from "@/components/waitlist-form";
import { HERO_IMAGES } from "@/lib/marketing/marketing-hero-images";
import { CONTACT_CTA_PRIMARY, CONTACT_HREF } from "@/lib/marketing/marketing-contact";
import { MARKETING_CASE_STUDIES } from "@/lib/marketing/case-studies";
import { cardSurfaceClass } from "@/lib/marketing/marketing-surfaces";

const glassCard = cardSurfaceClass("glass");

export type PublicArticleExample = {
  id: number;
  title: string;
  primaryKeyword: string;
  wordCount: number;
};

export type PublicRoadmapExample = {
  slug: string;
  industry: string;
  location: string;
};

type Props = {
  articles: PublicArticleExample[];
  roadmaps: PublicRoadmapExample[];
};

export function SuccessStoriesPageClient({ articles, roadmaps }: Props) {
  return (
    <MarketingPageShell
      hero={
        <PageHero
          badge="Success stories"
          titleLine1="Results from"
          titleLine2="client engagements"
          description="Anonymized outcomes from consulting programs run on goals.ac. Explore public examples or book a discovery call."
          backgroundImage={HERO_IMAGES.roadmaps.hero}
          ctas={[
            { label: CONTACT_CTA_PRIMARY, href: CONTACT_HREF, variant: "primary" },
            { label: "Browse roadmaps", href: "/roadmaps", variant: "ghost" },
          ]}
        />
      }
    >
      <MarketingSection bordered className="py-16" titleLine1="Proof you" titleLine2="can inspect">
        <div className="grid md:grid-cols-2 gap-6 mb-12">
          <div className={`${glassCard} p-6`}>
            <h3 className="font-bold text-lg mb-2 text-white">Public growth roadmaps</h3>
            <p className="text-sm text-white/65">Browse free 12-month B2B strategies generated by goals.ac.</p>
            {roadmaps.length > 0 && (
              <ul className="mt-3 text-xs text-white/50 space-y-1">
                {roadmaps.slice(0, 3).map((r) => (
                  <li key={r.slug}>
                    <Link href={`/roadmap/${r.slug}`} className="text-primary hover:underline">
                      {r.industry} · {r.location}
                    </Link>
                  </li>
                ))}
              </ul>
            )}
            <Link href="/roadmaps" className="inline-flex items-center gap-1 text-xs text-primary mt-4">
              Browse all →
            </Link>
          </div>
          <div className={`${glassCard} p-6`}>
            <h3 className="font-bold text-lg mb-2 text-white">Article quality demo</h3>
            <p className="text-sm text-white/65 mb-3">Every draft gets a /100 quality score covering structure, citations, schema, and more.</p>
            <div className="flex items-center gap-2 text-emerald-400 font-bold text-2xl">
              <TrendingUp className="h-5 w-5" /> 92/100
            </div>
            {articles.length > 0 && (
              <ul className="mt-4 space-y-2">
                {articles.slice(0, 3).map((a) => (
                  <li key={a.id}>
                    <Link href={`/seo-article/${a.id}`} className="text-sm text-primary hover:underline line-clamp-1">
                      {a.title}
                    </Link>
                    <span className="text-xs text-white/50 ml-1">· {a.wordCount} words</span>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {MARKETING_CASE_STUDIES.map((story) => (
            <Link key={story.slug} href={`/success-stories/${story.slug}`} className={`${glassCard} p-6 block`}>
              <p className="text-xs text-white/50 uppercase tracking-wide mb-2">{story.industry}</p>
              <h3 className="font-bold mb-2 text-white">{story.company}</h3>
              <p className="text-3xl font-bold text-primary">{story.value}</p>
              <p className="text-sm text-white/65">{story.metric} · {story.period}</p>
              <p className="text-sm text-white/65 mt-4 leading-relaxed line-clamp-3">{story.summary}</p>
              <span className="inline-flex items-center gap-1 text-xs text-primary mt-4">
                Read case study <ArrowRight className="h-3 w-3" />
              </span>
            </Link>
          ))}
        </div>
      </MarketingSection>

      <MarketingSection bordered className="py-16" titleLine1="Share your" titleLine2="results">
        <p className="text-white/65 mb-6 max-w-xl">Using goals.ac? Join the waitlist to be featured in our next success story.</p>
        <WaitlistForm featureKey="success-story" buttonLabel="Share my results" />
        <Link href={CONTACT_HREF} className="inline-flex items-center gap-1 text-sm text-primary mt-8 hover:underline">
          Or {CONTACT_CTA_PRIMARY.toLowerCase()} <ArrowRight className="h-4 w-4" />
        </Link>
      </MarketingSection>
    </MarketingPageShell>
  );
}
