/** Re-export Research UI from the dedicated research module. */
export {
  COMPETITOR_STAGES,
  ResearchCompetitorsView,
  ResearchOverviewView,
  ResearchRedditView,
  ResearchSignalsView,
  articleIdeaSourceLabel,
  buildAttackItems,
  buildResearchActionPaths,
  countKeywordSignals,
  displayCompetitorName,
  flattenCompetitorAnalysis,
  flattenCompetitorAnalysisList,
  flattenCompetitorAnalysisRow,
  formatAnalyzedAt,
  keywordFromInsight,
  loadSessionSignalThreads,
  pickTopArticleIdeas,
  researchSignalsStorageKey,
  saveSessionSignalThreads,
  sortWatchlist,
  type ArticleIdeaPeek,
  type AttackItem,
  type AttackItemKind,
  type CompetitorAnalysisResult,
  type CompetitorAnalysisRow,
  type CompetitorFormState,
  type KeywordSignalCounts,
  type RedditThread,
  type ResearchActionPaths,
  type ResearchLinkProps,
  type ThreatLevel,
} from "../research";
