// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nav/dual-rail-shell.tsx": () => import("../components/mockups/nav/dual-rail-shell.tsx"),
  "./components/mockups/nav/nested-single-sidebar.tsx": () => import("../components/mockups/nav/nested-single-sidebar.tsx")
};
